#pragma once

#include "common.h"
#include <map>
#include <string>

static const std::map<std::string, const char*> licenseeNames = {
    {"00",	 "None\0"                                },
    {"01",	 "Nintendo Research & Development 1\0"   },
    {"08",	 "Capcom\0"                              },
    {"13",	 "EA (Electronic Arts\0)"                },
    {"18",	 "Hudson Soft\0"                         },
    {"19",	 "B-AI\0"                                },
    {"20",	 "KSS\0"                                 },
    {"22",	 "Planning Office WADA\0"                },
    {"24",	 "PCM Complete\0"                        },
    {"25",	 "San-X\0"                               },
    {"28",	 "Kemco\0"                               },
    {"29",	 "SETA Corporation\0"                    },
    {"30",	 "Viacom\0"                              },
    {"31",	 "Nintendo\0"                            },
    {"32",	 "Bandai\0"                              },
    {"33",	 "Ocean Software/Acclaim Entertainment\0"},
    {"34",	 "Konami\0"                              },
    {"35",	 "HectorSoft\0"                          },
    {"37",	 "Taito\0"                               },
    {"38",	 "Hudson Soft\0"                         },
    {"39",	 "Banpresto\0"                           },
    {"41",	 "Ubi Soft1\0"                           },
    {"42",	 "Atlus\0"                               },
    {"44",	 "Malibu Interactive\0"                  },
    {"46",	 "Angel\0"                               },
    {"47",	 "Bullet-Proof Software2\0"              },
    {"49",	 "Irem\0"                                },
    {"50",	 "Absolute\0"                            },
    {"51",	 "Acclaim Entertainment\0"               },
    {"52",	 "Activision\0"                          },
    {"53",	 "Sammy USA Corporation\0"               },
    {"54",	 "Konami\0"                              },
    {"55",	 "Hi Tech Expressions\0"                 },
    {"56",	 "LJN\0"                                 },
    {"57",	 "Matchbox\0"                            },
    {"58",	 "Mattel\0"                              },
    {"59",	 "Milton Bradley Company\0"              },
    {"60",	 "Titus Interactive\0"                   },
    {"61",	 "Virgin Games Ltd.3\0"                  },
    {"64",	 "Lucasfilm Games4\0"                    },
    {"67",	 "Ocean Software\0"                      },
    {"69",	 "EA (Electronic Arts\0)"                },
    {"70",	 "Infogrames5\0"                         },
    {"71",	 "Interplay Entertainment\0"             },
    {"72",	 "Broderbund\0"                          },
    {"73",	 "Sculptured Software6\0"                },
    {"75",	 "The Sales Curve Limited7\0"            },
    {"78",	 "THQ\0"                                 },
    {"79",	 "Accolade\0"                            },
    {"80",	 "Misawa Entertainment\0"                },
    {"83",	 "lozc\0"                                },
    {"86",	 "Tokuma Shoten\0"                       },
    {"87",	 "Tsukuda Original\0"                    },
    {"91",	 "Chunsoft Co.8\0"                       },
    {"92",	 "Video System\0"                        },
    {"93",	 "Ocean Software/Acclaim Entertainment\0"},
    {"95",	 "Varie\0"                               },
    {"96",	 "Yonezawa/s�pal\0"                      },
    {"97",	 "Kaneko\0"                              },
    {"99",	 "Pack-In-Video\0"                       },
    {"9H",	 "Bottom Up\0"                           },
    {"A4",	 "Konami (Yu-Gi-Oh\0!)"                  },
    {"BL",	 "MTO\0"                                 },
    {"DK",	 "Kodansha\0"                            }
};